'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Config

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'cmdRegresar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdRegresar As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'Menu1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '<summary>
    'MultiView1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '<summary>
    'View2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents View2 As Global.System.Web.UI.WebControls.View

    '<summary>
    'Label1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtIdEmpleado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtIdEmpleado As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label21 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtNombreTec control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNombreTec As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboGrupo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboGrupo As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label6 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboColor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboColor As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'cmdRefreshColores control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdRefreshColores As Global.System.Web.UI.WebControls.Button

    '<summary>
    'Label7 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboEntradaLV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboEntradaLV As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label23 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboSalidaLV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboSalidaLV As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label24 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboComidaLV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboComidaLV As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label25 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label25 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtMinutosComidaLV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutosComidaLV As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label26 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboEntradaSabado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboEntradaSabado As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label27 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label27 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboSalidaSabado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboSalidaSabado As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label28 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboComidaSabado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboComidaSabado As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'Label29 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtMinComidaSabado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinComidaSabado As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdGuardarTec control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdGuardarTec As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdReorganizar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdReorganizar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'gvTecnicos control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents gvTecnicos As Global.System.Web.UI.WebControls.GridView

    '<summary>
    'View1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents View1 As Global.System.Web.UI.WebControls.View

    '<summary>
    'gvChips control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents gvChips As Global.System.Web.UI.WebControls.GridView
End Class
