'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Diagnostico

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'Panel1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'fechaRecepcion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaRecepcion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaRecepcion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaRecepcion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoRecepcion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoRecepcion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_CltEmpTrae control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_CltEmpTrae As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'cbl_VehiculoCortesia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_VehiculoCortesia As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'fechaEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_CltEmpRetira control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_CltEmpRetira As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'nombreCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'direccionCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents direccionCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'telefonoCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents telefonoCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaDiagnostico control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaDiagnostico As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'nombreAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreAsesor As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'noDiagnostico control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents noDiagnostico As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'noOrden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents noOrden As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaConfirmacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaConfirmacion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaConfirmacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaConfirmacion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoConfirmacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoConfirmacion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'nombreConfirmacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreConfirmacion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Conducido control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Conducido As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtVehiculoConducido control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtVehiculoConducido As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'lecturaVelocimetroCita control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lecturaVelocimetroCita As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'vehiculoPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents vehiculoPlacas As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'DOFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DOFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'vehiculoNombreModelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents vehiculoNombreModelo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'vehiculoModelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents vehiculoModelo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'vehiculoNoCarroceria control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents vehiculoNoCarroceria As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'vehiculoChasis control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents vehiculoChasis As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fenomeno1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fenomeno1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'telefonoContacto control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents telefonoContacto As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaContacto1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaContacto1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoContacto1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoContacto1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaContacto2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaContacto2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoContacto2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoContacto2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'nombreWalkAround control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreWalkAround As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaWalkAround control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaWalkAround As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaWalkAround control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaWalkAround As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoWalkAround control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoWalkAround As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_ConfirmaClt control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_ConfirmaClt As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'lecturaVeloRecibe control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lecturaVeloRecibe As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_Confirmar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_Confirmar As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'rbl_DesdeCuando control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_DesdeCuando As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtDesdeCuando control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtDesdeCuando As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Frecuencia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Frecuencia As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtFrecuencia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFrecuencia As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_Lugar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_Lugar As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'rdl_LuzAdvierte control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rdl_LuzAdvierte As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtLuzAdvierte control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtLuzAdvierte As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Condicion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Condicion As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'Label17 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtVelocimetro control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtVelocimetro As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label19 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Label18 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtTacometro control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTacometro As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label20 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cbl_Condicion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_Condicion As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'Label21 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label21 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtNoPersonas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNoPersonas As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label28 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtCargaVehiculo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCargaVehiculo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label29 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Label36 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label36 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtCargaRemolque control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCargaRemolque As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label37 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label37 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'rbl_Superficie control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Superficie As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtSuperficie control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtSuperficie As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Tiempo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Tiempo As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtTemperaturaExterna control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTemperaturaExterna As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label41 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label41 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'rbl_AC control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_AC As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtAC_Temperatura control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAC_Temperatura As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Label1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'detalleTrabajo1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents detalleTrabajo1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'detalleTrabajo2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents detalleTrabajo2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'detalleTrabajo3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents detalleTrabajo3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'detalleTrabajo4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents detalleTrabajo4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'nombreDiag control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreDiag As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaDiag control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaDiag As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaDiag control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaDiag As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoDiag control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoDiag As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'noLLave control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents noLLave As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'noBahia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents noBahia As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_ReparacionDiag control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_ReparacionDiag As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'rbl_Resultado control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Resultado As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'motivoResulta control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents motivoResulta As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_Seguir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_Seguir As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'causa1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents causa1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'causa2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents causa2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'causa3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents causa3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'causa4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents causa4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'DTC1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DTC1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'DTC2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DTC2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'DTC3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DTC3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'DTC4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DTC4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ddl_Status1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Status1 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Status2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Status2 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Status3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Status3 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Status4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Status4 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Datos1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Datos1 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Datos2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Datos2 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Datos3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Datos3 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ddl_Datos4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Datos4 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'cbl_InstGrtia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_InstGrtia As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'instruccion1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instruccion1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instruccion2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instruccion2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instruccion3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instruccion3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instruccion4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instruccion4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaIniInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaIniInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaIniInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaIniInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaIniInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaIniInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaIniInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaIniInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaIniInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaIniInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoIniInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoIniInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaIniInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaIniInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoIniInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoIniInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaIniInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaIniInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoIniInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoIniInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaIniInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaIniInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoIniInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoIniInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaFinInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaFinInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaFinInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaFinInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaFinInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaFinInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'fechaFinInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaFinInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaFinInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaFinInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoFinInst1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoFinInst1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaFinInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaFinInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoFinInst2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoFinInst2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaFinInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaFinInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoFinInst3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoFinInst3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaFinInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaFinInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoFinInst4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoFinInst4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaWork1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaWork1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaWork2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaWork2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaWork3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaWork3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaWork4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaWork4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoWork1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoWork1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoWork2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoWork2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoWork3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoWork3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoWork4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoWork4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_DTR1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_DTR1 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_DTR2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_DTR2 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_DTR3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_DTR3 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_DTR4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_DTR4 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'instTec1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instTec1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instCnf1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instCnf1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instTec2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instTec2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instCnf2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instCnf2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instTec3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instTec3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instCnf3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instCnf3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instTec4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instTec4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'instCnf4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents instCnf4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'tmexDestino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents tmexDestino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'tmexRespble control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents tmexRespble As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Tmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Tmex As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'fechaTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_StatusTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_StatusTmex As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_SolicitaTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_SolicitaTmex As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'fechaSolTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents fechaSolTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'horaSolTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents horaSolTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'minutoSolTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents minutoSolTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'nombreTmex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents nombreTmex As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'ImageButton1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'Button1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '<summary>
    'ImageButton2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'ImageButton3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'SqlDataSource40 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SqlDataSource40 As Global.System.Web.UI.WebControls.SqlDataSource

    '<summary>
    'Panel2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'Label2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'SqlDataSource_36 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SqlDataSource_36 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
