'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class File

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'cmdEliminar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdEliminar As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'divcont control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divcont As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
