'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrdenTecnico

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'pnlOrdenTecnico control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents pnlOrdenTecnico As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'txtTipoTrabajo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTipoTrabajo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_Refaccion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_Refaccion As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'txtLLaves control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtLLaves As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtBahia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtBahia As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHeadFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHeadFecha As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtNombreModelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNombreModelo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPlacas As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtNoOrden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNoOrden As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtNoTrabajo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNoTrabajo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtDOFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtDOFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAsesor As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtModelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModelo As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtSerie control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtSerie As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMotor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMotor As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTelefono_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTelefono_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtEmail_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtEmail_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Info_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Info_1 As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'rbl_CambioFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_CambioFecha As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtTrabajo_Otro control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTrabajo_Otro As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTrabajo_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTrabajo_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPieza_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPieza_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtAmount_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAmount_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCosto_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCosto_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ddl_Stock_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Stock_1 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtETA_11 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_11 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtETA_12 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_12 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTrabajo_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTrabajo_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPieza_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPieza_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtAmount_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAmount_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCosto_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCosto_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ddl_Stock_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Stock_2 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtETA_21 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_21 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtETA_22 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_22 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTrabajo_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTrabajo_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPieza_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPieza_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtAmount_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAmount_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCosto_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCosto_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ddl_Stock_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Stock_3 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtETA_31 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_31 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtETA_32 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_32 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTrabajo_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTrabajo_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPieza_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPieza_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtAmount_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtAmount_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCosto_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCosto_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCosto_5 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCosto_5 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ddl_Stock_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddl_Stock_4 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtETA_41 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_41 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtETA_42 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtETA_42 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaConta control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaConta As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraConta control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraConta As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoConta control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoConta As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtNombreConta control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNombreConta As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioFechaTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioFechaTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioHoraTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioHoraTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioMinutoTermino control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioMinutoTermino As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioFechaEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioFechaEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioHoraEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioHoraEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCambioMinutoEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCambioMinutoEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaIni_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaIni_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraIni_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraIni_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoIni_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoIni_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaFin_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaFin_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraFin_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraFin_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoFin_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoFin_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeHoraIni_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeHoraIni_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeMinutoIni_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeMinutoIni_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTecnico_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTecnico_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCalidad_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalidad_1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaIni_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaIni_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraIni_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraIni_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoIni_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoIni_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaFin_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaFin_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraFin_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraFin_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoFin_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoFin_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeHoraIni_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeHoraIni_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeMinutoIni_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeMinutoIni_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTecnico_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTecnico_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCalidad_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalidad_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaIni_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaIni_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraIni_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraIni_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoIni_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoIni_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaFin_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaFin_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraFin_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraFin_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoFin_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoFin_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeHoraIni_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeHoraIni_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeMinutoIni_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeMinutoIni_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTecnico_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTecnico_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCalidad_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalidad_3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaIni_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaIni_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraIni_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraIni_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoIni_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoIni_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaFin_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaFin_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraFin_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraFin_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoFin_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoFin_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeHoraIni_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeHoraIni_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTimeMinutoIni_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTimeMinutoIni_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtTecnico_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTecnico_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCalidad_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalidad_4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtComentario control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtComentario As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtObservacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtObservacion As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_CfrEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CfrEntrega As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'txtFechaAviso control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaAviso As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraAviso control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraAviso As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoAviso control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoAviso As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_CfrExplicacion_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CfrExplicacion_1 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_CfrExplicacion_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CfrExplicacion_2 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'txtCfrFechaEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrFechaEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrHoraEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrHoraEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrMinutoEntrega control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrMinutoEntrega As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_Cfr_Cliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Cfr_Cliente As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtCfrClienteOtro control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrClienteOtro As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrConfirmadoPor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrConfirmadoPor As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrNombre1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrNombre1 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrNombre2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrNombre2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrNombre3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrNombre3 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCfrNombre4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCfrNombre4 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPlanFechaPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPlanFechaPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPlanHoraPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPlanHoraPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPlanMinutoPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPlanMinutoPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_InfContacto control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_InfContacto As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'rbl_Info_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_Info_2 As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtTelefono_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTelefono_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtEmail_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtEmail_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtOtro_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtOtro_2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtRealFechaPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtRealFechaPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtRealHoraPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtRealHoraPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtRealMinutoPSFU control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtRealMinutoPSFU As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'rbl_PSFU_Cliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbl_PSFU_Cliente As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtPSFUClienteOtro control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPSFUClienteOtro As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_PSFUcontacto control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_PSFUcontacto As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'txtFechaLLamar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaLLamar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraLLamar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraLLamar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoLLamar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoLLamar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaRepetir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaRepetir As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtHoraRepetir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtHoraRepetir As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMinutoRepetir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMinutoRepetir As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPSFUnombre control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPSFUnombre As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPSFUconfirma control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPSFUconfirma As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cbl_LavaCoche control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_LavaCoche As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_CC_1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CC_1 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_CC_2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CC_2 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_CC_3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CC_3 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_CC_4 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_CC_4 As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'cbl_EntregaAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cbl_EntregaAsesor As Global.System.Web.UI.WebControls.CheckBoxList

    '<summary>
    'Image2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'ImageButton1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'Button1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '<summary>
    'ImageButton2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'ImageButton3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'SqlDataSource40 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SqlDataSource40 As Global.System.Web.UI.WebControls.SqlDataSource

    '<summary>
    'Panel1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'Label1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'SqlDataSource_36 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SqlDataSource_36 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
