'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pull_system4

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'floatdiv control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents floatdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'ImageButton2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'ImageButton1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'dhtml control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dhtml As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'lblCalendar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblCalendar As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblUsr control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblUsr As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtUpdateBoard control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtUpdateBoard As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'dchp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dchp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'Modelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Modelo As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Tolerancia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Tolerancia As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Orden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Orden As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Placas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Placas As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Service control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Service As Global.System.Web.UI.WebControls.Label

    '<summary>
    'DataList1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DataList1 As Global.System.Web.UI.WebControls.DataList

    '<summary>
    'dgTecnicosOrdenes control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dgTecnicosOrdenes As Global.System.Web.UI.WebControls.DataGrid
End Class
