'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pull_systemConfig4

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'scrmgr1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents scrmgr1 As Global.System.Web.UI.ScriptManager

    '<summary>
    'floatdiv control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents floatdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'ImageButton1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'dhtml control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dhtml As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'lblCalendar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblCalendar As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblUsr control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblUsr As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtUpdateBoard control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtUpdateBoard As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'dchp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dchp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'Modelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Modelo As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Tolerancia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Tolerancia As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Orden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Orden As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Placas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Placas As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Service control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Service As Global.System.Web.UI.WebControls.Label

    '<summary>
    'divInterfaz control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divInterfaz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'txtArchivo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtArchivo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '<summary>
    'cmdCargar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdCargar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cboChips control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboChips As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'cboCampos control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboCampos As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtCampoMostrar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCampoMostrar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'optOrientacion control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents optOrientacion As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'cboColorChip control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboColorChip As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'imgBtnMve_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnMve_DMS As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnDel_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnDel_DMS As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnCut_CHP control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnCut_CHP As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnPrs_CHP control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnPrs_CHP As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnUpd_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnUpd_DMS As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnRpt_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnRpt_DMS As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnTme_CHP control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnTme_CHP As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnStop control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnStop As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnInit control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnInit As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnIni control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnIni As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnFin control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnFin As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnOut_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnOut_DMS As Global.System.Web.UI.WebControls.ImageButton
End Class
