'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Refacciones

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'ScriptManager1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '<summary>
    'IMG1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents IMG1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '<summary>
    'Label1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'txtFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFecha As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdAgregar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdAgregar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdExport control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdExport As Global.System.Web.UI.WebControls.Button

    '<summary>
    'dgAusencias control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dgAusencias As Global.System.Web.UI.WebControls.DataGrid

    '<summary>
    'cmdMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'MPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MPGV As Global.AjaxControlToolkit.ModalPopupExtender

    '<summary>
    'PopupMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'PopupDragHandleMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupDragHandleMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'lblOp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblOp As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblModPieza control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModPieza As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtModPieza control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModPieza As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'lblModNoparte control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModNoparte As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtModNoparte control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModNoparte As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'lblModObservaciones control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModObservaciones As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtModObservaciones control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModObservaciones As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'OkButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OkButtonMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'NoButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents NoButtonMPGV As Global.System.Web.UI.WebControls.Button
End Class
