'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TTecnicosLavado

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'scrmgr1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents scrmgr1 As Global.System.Web.UI.ScriptManager

    '<summary>
    'wInterfaz control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents wInterfaz As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '<summary>
    'topfix0 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents topfix0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'leftfix control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents leftfix As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'floatdiv control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents floatdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'txtFind control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFind As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'imgFind control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgFind As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'SiteMapPath1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SiteMapPath1 As Global.System.Web.UI.WebControls.SiteMapPath

    '<summary>
    'lnkPrev control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lnkPrev As Global.System.Web.UI.WebControls.HyperLink

    '<summary>
    'lnkUp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lnkUp As Global.System.Web.UI.WebControls.HyperLink

    '<summary>
    'lnkNext control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lnkNext As Global.System.Web.UI.WebControls.HyperLink

    '<summary>
    'imgLogo1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgLogo1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '<summary>
    'dhtml control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dhtml As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'lblCalendar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblCalendar As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblUsr control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblUsr As Global.System.Web.UI.WebControls.Label

    '<summary>
    'dhtmlChp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dhtmlChp As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'dhMenu control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dhMenu As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'dchp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dchp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'Modelo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Modelo As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Tolerancia control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Tolerancia As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Orden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Orden As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Placas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Placas As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Service control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Service As Global.System.Web.UI.WebControls.Label

    '<summary>
    'divInterfaz control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divInterfaz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'imgRefrescar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgRefrescar As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'txtCalendar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalendar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'clCalendarEx control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents clCalendarEx As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtBuscar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtBuscar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'imgBuscar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBuscar As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'Menu1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '<summary>
    'divLeyendas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divLeyendas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'DataList2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents DataList2 As Global.System.Web.UI.WebControls.DataList

    '<summary>
    'leftfix0 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents leftfix0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'lstFind control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lstFind As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'btnStop1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnStop1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnInit control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnInit As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnIni control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnIni As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnFin1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnFin1 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnDgn_Kdw control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnDgn_Kdw As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnWrk_Kdw control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnWrk_Kdw As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnNoAutoriza control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnNoAutoriza As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'btnLvd control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnLvd As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgBtnOut_DMS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgBtnOut_DMS As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'cmdNuevo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdNuevo As Global.System.Web.UI.WebControls.Button

    '<summary>
    'MPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MPGV As Global.AjaxControlToolkit.ModalPopupExtender

    '<summary>
    'PopupMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'PopupDragHandleMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupDragHandleMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'divPopupDragHandleMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divPopupDragHandleMPGV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'divifra control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divifra As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'OkButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OkButtonMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'NoButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents NoButtonMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'txtComen control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtComen As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdGuardarComen control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdGuardarComen As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdCancelComen control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdCancelComen As Global.System.Web.UI.WebControls.Button

    '<summary>
    'btnFin control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnFin As Global.System.Web.UI.WebControls.Button

    '<summary>
    'Button2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cboStop control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboStop As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtComenDet control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtComenDet As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'btnStop control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnStop As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdCancelComenDet control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdCancelComenDet As Global.System.Web.UI.WebControls.Button
End Class
