'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zcrmCuestionarioDetalleInventario

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'ScriptManager1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '<summary>
    'pNLCT1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents pNLCT1 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'Imglogo1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Imglogo1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'LblTitulo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LblTitulo As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtOrden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtOrden As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'ImgBtnRef control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImgBtnRef As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'lblID control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'txtFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFecha As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'CboVIN control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents CboVIN As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'CboVIN2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents CboVIN2 As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'ImgBtnRef0 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ImgBtnRef0 As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'txtOP control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtOP As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtPLACAS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPLACAS As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtKILOMETRAJE control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtKILOMETRAJE As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFECHAE control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFECHAE As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFECHAEex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFECHAEex As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtMARCA control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMARCA As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtMODELO control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtMODELO As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtCOLOR control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCOLOR As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'PnlPReguntas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PnlPReguntas As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'LblLeyenda control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LblLeyenda As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Lblpregunta1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Lblpregunta1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'dgPreguntas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dgPreguntas As Global.System.Web.UI.WebControls.DataGrid

    '<summary>
    'pnlAdicionales control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents pnlAdicionales As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'lblObservacionesSeg control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblObservacionesSeg As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtObservacionesSeg control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtObservacionesSeg As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'lblObservacionesGer control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblObservacionesGer As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtObservacionesGer control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtObservacionesGer As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'pnlFooter control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents pnlFooter As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'pnlGuardar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents pnlGuardar As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'lblEstatusLlamada control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblEstatusLlamada As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cboEstatusLlamada control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboEstatusLlamada As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtFechaEstatus control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaEstatus As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFechaEstatusEx control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFechaEstatusEx As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'cmdGuardar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdGuardar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdVOC control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdVOC As Global.System.Web.UI.WebControls.Button
End Class
