'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zEntregas

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'ScriptManager1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'cmdBuscaPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdBuscaPlacas As Global.System.Web.UI.WebControls.Button

    '<summary>
    'txtPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtPlacas As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cboVehiculo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboVehiculo As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'cboColor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboColor As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'txtTorre2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTorre2 As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cboAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboAsesor As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'imgNuevoOK control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgNuevoOK As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'Menu1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '<summary>
    'dg1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dg1 As Global.System.Web.UI.WebControls.DataGrid

    '<summary>
    'dg2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dg2 As Global.System.Web.UI.WebControls.DataGrid

    '<summary>
    'cmdMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'MPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MPGV As Global.AjaxControlToolkit.ModalPopupExtender

    '<summary>
    'PopupMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'PopupDragHandleMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupDragHandleMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'lblOp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblOp As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf2 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf3 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblMSG control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblMSG As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblModCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModCliente As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblTorre control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblTorre As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblModfecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModfecha As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblModPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModPlacas As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblModVehiculo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblModVehiculo As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblEliminar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblEliminar As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtModFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModFecha As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtModFechaex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModFechaex As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtTorre control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTorre As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtModPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModPlacas As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtModCliente control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModCliente As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cboModVehiculo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cboModVehiculo As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'imgokDdModPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgokDdModPlacas As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'imgokModPlacas control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgokModPlacas As Global.System.Web.UI.WebControls.Button

    '<summary>
    'OkButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OkButtonMPGV As Global.System.Web.UI.WebControls.Button

    '<summary>
    'NoButtonMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents NoButtonMPGV As Global.System.Web.UI.WebControls.Button
End Class
