'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zFile

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'htop control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents htop As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'hleft control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents hleft As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'hoffsettop control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents hoffsettop As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'hoffsetleft control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents hoffsetleft As Global.System.Web.UI.HtmlControls.HtmlInputText

    '<summary>
    'txtNoorden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtNoorden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '<summary>
    'utxtArchivo control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents utxtArchivo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '<summary>
    'ucmdCargar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ucmdCargar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdActualizar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdActualizar As Global.System.Web.UI.WebControls.Button
End Class
