'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zRecepcionAsesoresEntrega

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'ScriptManager1b control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ScriptManager1b As Global.System.Web.UI.ScriptManager

    '<summary>
    'lblIdAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblIdAsesor As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'rdlAsesores control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rdlAsesores As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'rdlStatus control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rdlStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '<summary>
    'txtI control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtI As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtIex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtIex As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtF control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtF As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtFex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFex As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtFind control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtFind As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdBuscar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdBuscar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'dg1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dg1 As Global.System.Web.UI.WebControls.DataGrid
End Class
