'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zRecepcionAsesoresD

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'lblIdAsesor control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblIdAsesor As Global.System.Web.UI.WebControls.Label

    '<summary>
    'cmdServicios control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdServicios As Global.System.Web.UI.WebControls.Button

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'ToolkitScriptManager1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '<summary>
    'MPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MPGV As Global.AjaxControlToolkit.ModalPopupExtender

    '<summary>
    'PopupMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'PopupDragHandleMPGV control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupDragHandleMPGV As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'txtTorre control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtTorre As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtOrden control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtOrden As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdCancelar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdCancelar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'divServiciosH control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divServiciosH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'cmdGuardar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdGuardar As Global.System.Web.UI.WebControls.Button

    '<summary>
    'cmdMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdMPGV2 As Global.System.Web.UI.WebControls.Button

    '<summary>
    'MPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MPGV2 As Global.AjaxControlToolkit.ModalPopupExtender

    '<summary>
    'PopupMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupMPGV2 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'PopupDragHandleMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PopupDragHandleMPGV2 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'divPopupDragHandleMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divPopupDragHandleMPGV2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'lblOp control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblOp As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf2 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblInf3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblInf3 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lblMSG control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lblMSG As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lbllblModfecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lbllblModfecha As Global.System.Web.UI.WebControls.Label

    '<summary>
    'lbllblModComentarios control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents lbllblModComentarios As Global.System.Web.UI.WebControls.Label

    '<summary>
    'txtModFecha control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModFecha As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'txtModFechaex control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModFechaex As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'txtModComentarios control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtModComentarios As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'OkButtonMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OkButtonMPGV2 As Global.System.Web.UI.WebControls.Button

    '<summary>
    'NoButtonMPGV2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents NoButtonMPGV2 As Global.System.Web.UI.WebControls.Button

    '<summary>
    'txtCalendar control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtCalendar As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'clCalendarEx control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents clCalendarEx As Global.AjaxControlToolkit.CalendarExtender

    '<summary>
    'dg1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dg1 As Global.System.Web.UI.WebControls.DataGrid

    '<summary>
    'dgLibres control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents dgLibres As Global.System.Web.UI.WebControls.DataGrid
End Class
