'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class zRecepcionAsesoresServiciosOrden

    '<summary>
    'Head1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '<summary>
    'form1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '<summary>
    'ScriptManager1b control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ScriptManager1b As Global.System.Web.UI.ScriptManager

    '<summary>
    'Image1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '<summary>
    'imgSalir control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSalir As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'LBLPLACAS control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LBLPLACAS As Global.System.Web.UI.WebControls.Label

    '<summary>
    'LBLORDEN control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LBLORDEN As Global.System.Web.UI.WebControls.Label

    '<summary>
    'LBLVIN control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LBLVIN As Global.System.Web.UI.WebControls.Label

    '<summary>
    'Label1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '<summary>
    'divServiciosH control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents divServiciosH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'gvServiciosH control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents gvServiciosH As Global.System.Web.UI.WebControls.GridView
End Class
